FROM ubuntu
MAINTAINER Amir Haghighati <haghighati.amir@gmail.com>

ENV HOME=/var/www
ENV TERM=xterm
ENV SHELL=bash
WORKDIR /
EXPOSE 80

RUN echo "Initializing script..." && \
    apt-get update && \
    apt-get -y upgrade && \
	echo "Installing Nginx..." && \
	apt-get install -y nginx && \
	echo "Adding rule to 'ufw' firewall" && \
	ufw allow 'Nginx HTTP'
    
RUN	echo "Installing PHP 7 and its components: [cli,common,fpm,curl,gd, intl,zip,xsl,mbstring,mysql]..." && \
	apt-get install -y php7.0-cli \
	apt-get install -y php7.0-common \
	apt-get install -y php7.0 \
	apt-get install -y php7.0-fpm \
	apt-get install -y php7.0-curl \
	apt-get install -y php7.0-gd \
	apt-get install -y php7.0-intl \
	apt-get install -y php7.0-zip \
	apt-get install -y php7.0-xsl \
	apt-get install -y php7.0-mbstring \
	# required for installing xdebug
	apt-get install -y php7.0-dev

RUN	echo "Configuring PHP..." && \
	sudo sed -i s/\;cgi\.fix_pathinfo\s*\=\s*1/cgi.fix_pathinfo\=0/ /etc/php/7.0/fpm/php.ini

	# Composer
RUN	echo "Installing Composer..." && \
	curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer 

RUN	echo "Installing Composer Asset plugin..." && \
	composer global require "fxp/composer-asset-plugin:~1.1"

RUN	echo "Restarting PHP, Nginx and MySQL services..." && \
	/etc/init.d/php7.0-fpm restart && \
	/etc/init.d/nginx restart
	
RUN	echo "Installing MongoDB..." && \
	apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927 && \
	echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list && \
	apt-get update && \
	apt-get install -y --allow-unauthenticated mongodb-org && \
	echo '[Unit]
Description=High-performance, schema-free document-oriented database
After=network.target
[Service]
User=mongodb
ExecStart=/usr/bin/mongod --quiet --config /etc/mongod.conf
[Install]
WantedBy=multi-user.target' > /etc/systemd/system/mongodb.service && \
	systemctl start mongodb && \
	systemctl status mongodb && \
	systemctl enable mongodb && \

RUN	echo "Installing GIT..." && \
	apt-get install -y git

RUN	echo "Removing unneeded dependencies" && \
	apt-get autoremove

# gulp-cli
#RUN npm install --global gulp-cli

# Cleanup
#RUN rm -rf /var/cache/apt && rm -rf /var/lib/apt

# Permissions
RUN chown www-data:www-data -R /root

# PHP-FPM
RUN mkdir -p /run/php
COPY conf/www.conf /etc/php/7.0/fpm/pool.d/www.conf
COPY conf/php.ini /etc/php/7.0/fpm/php.ini

# Nginx
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/nginx-default /etc/nginx/conf.d/default.conf

# www-data user
RUN mkdir -p /var/www && chown -R www-data:www-data /var/www && \
    ln -s /var/www/ /home/www-data

# Supedvisord
COPY conf/supervisord.conf /etc/supervisord.conf

# Bin
COPY bin /bin

VOLUME /var/www
ENTRYPOINT ["entrypoint"]
